### PR TITLE
Addition of methods to improve attributes handling and inner text for tags.

### PR DESCRIPTION
**Pull request by satansly**
Addition of interface methods to HasAttributes to get and set attributes for the implementing class.
Addition of getInnerText() and setInnerText(s) to allowing setting inner text for xml tags.
Implementation of new methods in implementing class of HasAttributes.
SoapSerialization additional code to handle attributes.

### CODE REVIEW

**Comment by robocik** [comment]
I've analyzed a changes in this commit and I don't undestand why do we need a method getAttribute in HasAttributes? What is the difference between getAttribute and getAttributeInfo?
Also I'm wonder if methods getInnerText and setInnerText should be added to KvmSerializable interface. I would rather create a separate interface with these method because these methods are required only in few situations (in most cases we don't use them - for example SoapObject class has empty implementation). Second problem is that now many existing code are broken.

**Comment by satansly** [comment]
Is the requirement of having to implement the interface methods breaking
your code, or is it a problem at runtime?

**Comment by robocik** [comment]
Problem is with implementing interface. There are many projects which use ksoap2 library. My company (http://easywsdl.com) has hundreds customers which uses ksoap2 and now if they want to use a latest version, they must manually change every class which implements this interface. From my company point of view this is not a problem because we can update our generator to use a latest version. But now I'm talking in general that it would be safer to move these methods to separate interface. In this case if somebody needs getInnerText method, then he will implement this additional interface and that's it.

Can you also tell me what is the difference between getAttribute and getAttributeInfo?

**Comment by satansly** [comment]
I made these changes almost a year ago so I am not sure why I made these
two. You are right about breaking up inner text methods to another
interface. I will look into removing getAttribute() if it is a redundancy,
and create a pull request. Thanks for the feedback.

**Comment by satansly** [comment]
Ok. Reviewing the code, I see what the purpose for getAttribute(the name is
misleading) was. It is to set the attribute value. Its use is more similar
to setAttribute. Where setAttribute copies 'value' of the passed
attributeinfo to a local attributeinfo with same name. The getAttribute
copies 'value' from the local attributeinfo to the passed attributeinfo of
same name. I think more appropriate signatures would be.

void setAttributeValue(AttributeInfo info)
void getAttributeValue(AttributeInfo info)

If you have a different suggestion do let me know. Those are the intentions
for these two interface methods.

**Comment by robocik** [comment]
Now it is more clear for me. But I see a few problems with these methods:
There are no implementation of these method in AttributeContainer class. You have added methods to the interface HasAttribute (I assume that your code requires these methods) but from the ksoap2 point of view these methods do nothing. So I don't see a reason why they must exists in the base class (AttributeContainer) and all ksoap2 users have to implement them (mostly with empty body).
Do you think that these methods are necessary? What I mean is that maybe in your code you can use existing methods to finish your task?
If you think that they are very helpful and other developers will also use them then I think it would be better to implement this in the same way as getInnerText methods - create a separate interface for them. In this case, only developers who need this functionality must implement it. The rest will not even notice any change.

**Comment by satansly** [comment]
The requirement of getAttribute(),setAttribute() is during serialization of
request/response respectively.  We want to make sure we set the value of
attribute before reading into soapobject or writing it with the serializer.
The function getAttribute() is not used in the best way in the current
framework but for a set of helper classes that I will add in near future,
that will ease the usage of ksoap2  further, using annotations on POJO
objects to auto-hydrate using reflection. I would vouch for these methods
staying in there for next release if those changes make it to main branch.
Regarding setinnertext and getinnertext, and would only be implemented if
an object requires inner text for one of its property while
reading/writing. Also because KvmSerializable is the interface implemented
for everything ksoap2 related serialization while hasattributes is probably
less commonly used.

**Comment by robocik** [comment]
My main worry about this is that I prefer extend libraries by adding a new interface or plug a new behavior in another, non-invasive way.Of course adding two new methods to any existing interface (KvmSerializable, HasAttributes or other) is not a big deal, but when we think about future of the library then if new methods will be added too often then in the future a developer who needs to create a custom object which implements any of the main ksoap2 interfaces, he would have to add many empty methods. And for me it is better that only developer who wants to use a new feature, he would implement new methods.
Of course I don't exactly know how you use these methods and what new features you are going to add to ksoap2 in the future so my last sentences are not strict related with your commits, but rather this is a general thoguht. So maybe someone else gives us another opinion.

But nevertheless, thanks for your work on improving this library:)

**Comment by satansly** [comment]
Thanks for the the appreciation. By design the attribute value
setter/getter belong in HasAttributes. Implementing the interface implies
the need for attributes serialization/deserialization. However innertext is
not something every soap request/response requires, I will factor that out
and submit a fix soon :)

**Comment by mosabua** [comment]
Sounds good @satansly .. and thanks a lot for the feedback @robocik ... if you have any other concerns .. lets make sure we resolve them before I cut another release.

**Comment by robocik** [comment]
@mosabua you are right that my feedback should be before the release. Next time I will check pullrequests much faster:)

**Comment by mosabua** [comment]
Thats not what I meant @robocik .. all your help is great. I just meant we have to make sure we release only after your concerns are addressed.

**Comment by robocik** [comment]
I will do my best

**Comment by mosabua** [comment]
@robocik I have merged your other changes now. Looks great. Do you want to adapt this work here with @satansly so we can cut a new release without breaking API too much?

**Comment by robocik** [comment]
In my changes I've already make some implementation related with setInnerText and getInnerText methods in SoapObject class. But of course I'm ready to work with @satansly to adapt his work before new release.
@satansly you've mentioned that you are going to make more changes in the ksoap library. Have you started this?

**Comment by satansly** [comment]
@robocik, I hadn't yet but will do that tomorrow. I will create another
pull request after separating the interfaces.

**Comment by satansly** [comment]
Refactored and created a pull request. Have a look guys.

**Comment by mosabua** [comment]
Had a look. +1 from me.

**Pull request merged**
