### PR TITLE
Inner Text methods refactored out of kvmSerializable

### PR DESCRIPTION
**Pull request by satansly**

### CODE REVIEW

**Comment by mosabua** [comment]
+1 from me. wydt @robocik

**Comment by robocik** [comment]
Looks good for me. One small request. Can you change SoapObject class to also implement this HasInnerText interface? Please notice that I've already did an implementation for setInnerText and getInnerText methods in SoapObject so you should only add this interface at the beginning of the SoapObject class (and nothing more).
If you have questions then let me know. Thanks for you contribution

**Comment by mosabua** [comment]
I agree with @robocik but merged for now. Ideally send another pull request with those additional changes.

**Comment by satansly** [comment]
Added the interface to SoapObject and created pull request.

**Pull request merged**
